--- 
- name: Enable Internet Services
  hosts: serverb.lab.example.com
  become: yes
  tasks:
    - name: Install yum reop
      yum: 
        name:
          - httpd
          - mariadb-server
          - php
          - php-mysqlnd
          - firewalld
        state: latest

    - name: Enable firewall service
      service:
        name: firewalld
        state: started
        enabled: true

    - name: configure firewall for http
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    - name: start httpd servie
      service:
        name: httpd
        state: started
        enabled: true

    - name: enabled mariadb service
      service:
        name: mariadb
        state: started
        enabled: true
        
    - name: Download foo.conf
      get_url:
        url: http://materials.example.com/labs/playbook-review/index.php
        dest: /var/www/html/
        mode: '0644'

- name: Test web page on conrol node
  hosts: localhost
  tasks:
    - name: browse
      uri:
        url: http://serverb.lab.example.com
        status_code: 200








